# Generated by Django 4.2.3 on 2024-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='object_id',
            field=models.CharField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent_id',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
    ]
