# Generated by Django 5.0.2 on 2024-05-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
