# Generated by Django 4.2.3 on 2023-07-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_numbers',
            new_name='phone_number',
        ),
    ]
