apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles-pv-user-microservice
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 512Mi
  storageClassName: cs-fuse-smile-sales
  mountOptions:
    - implicit-dirs
    - uid=1001
    - gid=3003
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: smile-sales-bucket