apiVersion: apps/v1
kind: Deployment
metadata:
  name: dramatiq-crontab
  namespace: smile-sales-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dramatiq-crontab
  template:
    metadata:
      labels:
        app: dramatiq-crontab

    spec:
      serviceAccountName: gke-user

      containers:
        - image: ghost04/smile-sales-user-microservice:latest
          command: [ "python", "manage.py", "crontab"]
          imagePullPolicy: Always
          name: dramatiq-crontab-container
          envFrom:
            - secretRef:
                name: web-secrets
            - configMapRef:
                name: web-config-map
