apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles-pv-user-microservice
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  storageClassName: cs-fuse-smile-sales
  mountOptions:
    - only-dir=staticfiles
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: smile-sales-bucket