apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles-pvc
  namespace: smile-sales-users
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  volumeName: staticfiles-pv-user-microservice
  storageClassName: cs-fuse-smile-sales