# Generated by Django 5.0.2 on 2024-05-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyvieweditem',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
