# Generated by Django 5.0.2 on 2024-05-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_recentlyvieweditem_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyvieweditem',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
