# Generated by Django 5.0.2 on 2024-05-09 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_recentlyvieweditem_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyvieweditem',
            name='view_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
