# Generated by Django 5.0.2 on 2024-05-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_recentlyvieweditem_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyvieweditem',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
